### PR TITLE
Update missing and confusing deps.

### PR DESCRIPTION
**Pull request by kylev**
Trying to put together a dev env to do some debugging was a bit painful, so I kept notes and fixed the problems.

The first change pulls CoFH from an ["ivy" artifact](https://gradle.org/docs/current/dsl/org.gradle.api.artifacts.repositories.IvyArtifactRepository.html) rather than with copied source code. This is a more common practice and is less confusing to IntelliJ/Eclipse, and makes compiling against new versions as they come out super easy. If CoFH sets up a Maven repo later, it's easy to convert to that.

CodeChicken *does* have a Maven repo. So I deleted those .jar files (CodeChicken* and NEI) and converted them to dependencies in the `build.gradle`. Doing a `gradlew check` verifies that they download cleanly. And now I can check out the whole Mariculture repo and do a standard developer setup (`gradlew setupDecompWorkspace idea`) and be up and running in IntelliJ in a few minutes.

I'm happy to convert more of the dependencies and improve the build system if you'd like.

### CODE REVIEW

**Comment by kylev** [comment]
And, yes: I'm fully aware that this looks crazy-big. However, the 9000+ deleted lines are almost entirely code that comes from other projects. There are zero changes to Mariculture .java files.

**Comment by kylev** [comment]
I just verified that it works via another computer: someone wanting to contribute bug fixes can check out my branch and get a 1.7.10 Minecraft with Mariculture up and running in minutes:

```
git clone git@github.com:kylev/Mariculture.git
cd Mariculture
git checkout kv_gradle_deps
gradlew setupDevWorkspace runClient
# Install Enchiridion per prompt
gradlew runClient
```

The Enchiridion prompt doesn't happen in IntelliJ IDEA, but that's probably a separate issue to address.

**Comment by kylev** [comment]
Note, a [second round of improvements](https://github.com/kylev/Mariculture/compare/kv_gradle_deps...kv_gradle_deps_2) is ready to clean even more stuff up if you don't object to this pull request.

**Comment by joshiejack** [comment]
A lot of this is from when I was originally setting things up. Things were either broken at the time or would just crash me in dev. I also used the libs as it was 10 x easier for me than adding a bunch of random stuff that I have no idea what they do (no clue about gradle :P). If you can confirm that you can run the game, after setting stuff up from scratch and not crash when opening your inventory and other issues >.>, I can pull this. Also since I have no idea about this stuff, does using the maven/other stuff etc download the file each time to compile? (Probably a stupid question). (Last time I tried to use the TConstruct one it kept failing/corrupting.

**Comment by kylev** [comment]
I confirmed, on a completely separate machine, that I was able to:
- Clone my fork of your repo
- Check out this branch
- Run 2 gradle commands to set up the workspace
- Launch Minecraft, create a world, open my inventory, grab fish nets from creative, and place those nets atop water.

It looks like the rest of the modding world is slowly coming up to speed with Gradle/Maven. I'm a full-time professional software dude that does a lot with tooling and builds, so I'm trying to donate some of that expertise to modders and have started some tutorials. Hopefully soon the community will have lots of idioms and examples of exactly this sort of thing so people *don't* have to become experts, nor do they have to make giant copies of source code into their own trees.

Let me know if you'd like me to do any other testing or confirmation.

**Comment by kylev** [comment]
Oh, and as for downloading, it gradle/maven only update and download dependencies when you tell it to (usually during tasks like `setupDevWorkspace`). Day to day, it keeps a cached set of dependencies in `/.gradle/caches/` (OSX), so builds are still nearly instant (no re-downloading).

**Comment by joshiejack** [comment]
Ok, that was really my only concern because my internet has a data limit >.>.

I won't be able to check this out myself until Friday though. But feel free to update clean anything else where neccessary.

**Comment by joshiejack** [comment]
Can you switch this to the 1.2.5 branch. I'm gonna leave it alone in the 1.2.4

**Comment by kylev** [comment]
Rebased and re-parented in #263.

**Pull request closed without merging**
