### PR TITLE
fishing loot chance fixes

### PR DESCRIPTION
**Pull request by Kiyaku**
fixed RARE loot checker using junk chance values and vice versa
multiply chances by 10 so it falls within the 0..1000 range

### CODE REVIEW

**Comment by Kiyaku** [comment]
If i fix this in the 1.2.4 branch, could we get a new build for that as well that i can use in a third party public modpack? 
Also kinda wanna look at the Luck of the Sea enchantment, it seems like it uses a completely different check for rarity and ignores the rod chance values.

**Comment by joshiejack** [comment]
Feel free. I'd just grab the build from jenkins and upload that. I do wish I'd got around to finishing the 1.3.0 version though, it made so many good changes. Technically I could just make the couple of fish textures it needed and forget about updating the docs. But I know I need to focus on 1.8/1.9. Sorry for rambling xD

**Comment by joshiejack** [comment]
As well as it fixing a couple annoying bugs.

**Comment by Kiyaku** [comment]
Haha gotcha, yeah i noticed the fish all had the vanilla fish texture. I've always wanted to learn minecraft modding so this has been very interesting so far heh. I'll probably keep messing around on a 1.3 fork just to learn from it as well (trying to figure out why the fish all are listed as Raw Fish with the vanilla texture heh).

**Comment by joshiejack** [comment]
You need to add -Dfml.coreMods.load=mariculture.fishery.VanillaOverride  to the java arguments

**Comment by Kiyaku** [comment]
aha! that fixed it thanks! :D

**Pull request merged**
